Billetera2/Models/Movimiento.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;



namespace Billetera2.Models
{
    public class Movimiento
    {
        
        public enum Tipo
        {

            Ingreso,
            Egreso



        }

        [Key]
        public Guid Id { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [Range(1, 999999999, ErrorMessage = "El valor debe estar entre {1} y {2}")]
        public double Monto { get; set; }

        [MaxLength(180, ErrorMessage = "El maximo permitido para el {0} es {1}")]
        public string Descripcion { get; set; }

        [Required(ErrorMessage = "Debe informar la fecha su movimiento")]
        [Display(Name = "Fecha del movimiento")]
        [DataType(DataType.Date)]
        public DateTime Fecha { get; set; }

        //[MaxLength(3, ErrorMessage = "El maximo permitido para el {0} es {1}")]
        //[RequiredEnumField(ErrorMessage = "Address type is required.")]
        public Tipo TipoMovimiento { get; set; }


        [Required]
        [ForeignKey(nameof(Usuario))]
        public Guid UsuarioId { get; set; }
        public Usuario Usuario { get; set; }


    }
}

Billetera2/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;


namespace Billetera2.Models
{
    public class Usuario
    {
        
        [Key]
        public Guid Id { get; set; }

        [MinLength(4, ErrorMessage = "El usuario debe tener 4 caracteres como minimo")]
        [MaxLength(180, ErrorMessage = "El maximo permitido para el {0} es {1}")]
        public string Nombre { get; set; }
        [MinLength(4, ErrorMessage = "La contraseña debe tener 4 caracteres como minimo")]
        [MaxLength(8, ErrorMessage = "El maximo permitido para el {0} es {1}")]
        public string Contrasenia { get; set; }


        public IEnumerable<Movimiento> Movimientos { get; set; }




    }
}

Billetera2/Controllers/MovimientoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Billetera2.Models;
using Billetera2.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace Billetera2.Controllers
{
    public class MovimientoController : Controller
    {
        private readonly BilleteraDatabaseContext _context;

        public MovimientoController(BilleteraDatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var session = HttpContext.Session.GetString("usuarioSession");
            if (session == null)
            {
                return NotFound();
            }
            var usuario = JsonConvert.DeserializeObject<Usuario>(session);
            List<Movimiento> movimientos = _context.Movimientos.Where(m => m.UsuarioId == usuario.Id).ToList();
            ViewBag.UsuarioID = usuario.Id;

            return View(movimientos);
        }

        public List<Movimiento> GetAllMovimientos()
        {
            var session = HttpContext.Session.GetString("usuarioSession");
            if (session == null)
            {
                return new List<Movimiento>();
            }
            var usuario = JsonConvert.DeserializeObject<Usuario>(session);
            List<Movimiento> movimientos = _context.Movimientos.Where(m => m.UsuarioId == usuario.Id).ToList();
            ViewBag.UsuarioID = usuario.Id;
            return movimientos.ToList();
        }

        public IActionResult Create()
        {
            var session = HttpContext.Session.GetString("usuarioSession");
            if (session == null)
            {
                return NotFound();
            }
            var usuario = JsonConvert.DeserializeObject<Usuario>(session);

            Movimiento movimiento = new Movimiento();
            movimiento.UsuarioId = usuario.Id;

            return View(movimiento);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Monto,Descripcion,Fecha,TipoMovimiento,UsuarioId")] Movimiento movimiento)
        {
            if (ModelState.IsValid)
            {
                movimiento.Id = Guid.NewGuid();
                var session = HttpContext.Session.GetString("usuarioSession");
                if (session == null)
                {
                    return NotFound();
                }
                var usuario = JsonConvert.DeserializeObject<Usuario>(session);
                var movimientos = _context.Movimientos
                                            .Where(m => m.UsuarioId == usuario.Id);
                double mTotal = 0;
                foreach (var mov in movimientos)
                {
                    if (mov.TipoMovimiento == Movimiento.Tipo.Egreso)
                    {
                        mTotal -= mov.Monto;
                    }
                    else
                    {
                        mTotal += mov.Monto;
                    }
                }
                if (movimiento.TipoMovimiento == Movimiento.Tipo.Egreso)
                {
                    if (movimiento.Monto <= mTotal)
                    {
                        _context.Add(movimiento);

                    }
                }
                else
                {
                    _context.Add(movimiento);
                }
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(movimiento);
        }

        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movimiento =  _context.Movimientos.FirstOrDefault(m => m.Id == id);
            if (movimiento == null)
            {
                return NotFound();
            }

            return View(movimiento);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var movimiento = await _context.Movimientos.FindAsync(id);
            _context.Movimientos.Remove(movimiento);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mov = await _context.Movimientos.FindAsync(id);
            if (mov == null)
            {
                return NotFound();
            }
            return View(mov);
        }

      
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Monto,Descripcion,Fecha,UsuarioId,TipoMovimiento")] Movimiento mov)
        {
            if (id != mov.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mov);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovimientoExists(mov.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { id = mov.UsuarioId });
            }
            return View(mov);
        }

        private bool MovimientoExists(Guid id)
        {
            return _context.Movimientos.Any(e => e.Id == id);
        }
    }
}

Billetera2/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Billetera2.Context;
using Billetera2.Models;
using Billetera2.ViewModels;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace Billetera2.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly BilleteraDatabaseContext _context;

        public UsuarioController(BilleteraDatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Usuarios.ToList());
        }

        public IActionResult Login()
        {
            return View();
        
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Remove("usuarioSession");
            return RedirectToAction("Index", "Home");

        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Movimientos(Guid id)
        {
            var session = HttpContext.Session.GetString("usuarioSession");
            if (session == null)
            {
                return NotFound();
            }
            var usuario = JsonConvert.DeserializeObject<Usuario>(session);
            Movimiento movimiento = new Movimiento();
            movimiento.UsuarioId = id;

            return View(movimiento);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Contrasenia")] Usuario usuario)
        {
            if (ModelState.IsValid && !String.IsNullOrEmpty(usuario.Nombre))
            {
                usuario.Id = Guid.NewGuid();
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                HttpContext.Session.SetString("usuarioSession", JsonConvert.SerializeObject(usuario));
                return RedirectToAction(nameof(Details));

            }
            return View(usuario);
        }

        public IActionResult Delete()
        {
            var session = HttpContext.Session.GetString("usuarioSession");
            if (session == null)
            {
                return NotFound();
            }
            var usuario = JsonConvert.DeserializeObject<Usuario>(session);

            var user =  _context.Usuarios.FirstOrDefault(m => m.Id == usuario.Id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed()
        {
            var usuario = JsonConvert.DeserializeObject<Usuario>(HttpContext.Session.GetString("usuarioSession"));
            var user = await _context.Usuarios.FindAsync(usuario.Id);
            _context.Usuarios.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { id = user.Id });
        }


      
        public IActionResult Details()
        {
            var session = HttpContext.Session.GetString("usuarioSession");
            if (session == null)
            {
                return NotFound();
            }
            var usuario = JsonConvert.DeserializeObject<Usuario>(session);
            

            var movimientos =  _context.Movimientos
                                            .Where(m => m.UsuarioId == usuario.Id).ToList();
            double mTotal = 0;
            
            foreach (var mov in movimientos) {
                if (mov.TipoMovimiento == Movimiento.Tipo.Egreso)
                {
                    mTotal -= mov.Monto;
                }
                else
                {
                    mTotal += mov.Monto;
                }
            }
            

            if (usuario == null)
            {
                return NotFound();
            }

            ViewBag.total = mTotal;
            ViewData["movimientos"] = movimientos.Take(5);
            ViewData["total"] = mTotal;
            return View(usuario);
        }



        public IActionResult Edit()
        {
            var session = HttpContext.Session.GetString("usuarioSession");
            if (session == null)
            {
                return NotFound();
            }
            var usuario = JsonConvert.DeserializeObject<Usuario>(session);
            return View(usuario);
        }

 
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id,Nombre,Contrasenia")] Usuario user)
        {
            var session = HttpContext.Session.GetString("usuarioSession");
            if (session == null)
            {
                return NotFound();
            }
            var usuario = JsonConvert.DeserializeObject<Usuario>(session);

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details));
            }
            return View(user);
        }

        private bool UsuarioExists(Guid id)
        {
            return _context.Usuarios.Any(e => e.Id == id);
        }

        private bool UsuarioNameExists(string nombre)
        {
            return _context.Usuarios.Any(e => e.Nombre == nombre);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login([Bind("Id,Nombre,Contrasenia")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                usuario.Id = Guid.NewGuid();
                if (UsuarioNameExists(usuario.Nombre))
                {
                    var user = _context.Usuarios.FirstOrDefault(m => m.Nombre == usuario.Nombre);
                    if (usuario.Contrasenia == user.Contrasenia)
                    {
                        HttpContext.Session.SetString("usuarioSession", JsonConvert.SerializeObject(user));
                        return RedirectToAction(nameof(Details));

                    }
                }
            }
            return View();
        }
    }

}

Billetera2/Views/Usuario/Create.cshtml
@model Billetera2.Models.Usuario

@{ ViewData["Title"] = "Create Usuario"; }

<h4>Crea tu cuenta</h4>

<div class="row justify-content-center">
    <div class="col-md-4 flex-column">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" required />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contrasenia" class="control-label">Contraseña</label>
                <input asp-for="Contrasenia"  type="password"  class="form-control" required />
                <span asp-validation-for="Contrasenia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Billetera2/Views/Usuario/Delete.cshtml
@model Billetera2.Models.Usuario

@{ ViewData["Title"] = "Delete"; }



<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movimiento</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Contrasenia)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Contrasenia)
        </dd>
        @*<dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movimientos.ToList().Count())
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayNameFor(model => model.Movimientos.ToList().Count())
        </dd>*@
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Billetera2/Views/Usuario/Details.cshtml
@model Billetera2.Models.Usuario

@{ ViewData["Title"] = "Resumen"; }


<div class="justify-content-center">
    @*<h4>Usuario</h4*@

    <div class="card flex">
        <h5 class="card-header">Hola, @Model.Nombre!</h5>
        <div class="card-body">
            <h1 class="display-5 card-title text-center">Tu balance actual es de</h1>
            <h1 class="display-3 text-center">$@ViewData["total"].ToString()</h1>
            <a asp-controller="Movimiento" asp-action="Index" class="btn btn-primary">Ver todos mis movimientos</a>
        </div>
    </div>
    <div id="accordion">
        <div class="card">
            <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Ultimos Movimientos
                    </button>
                </h5>
            </div>
            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="card-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Monto</th>
                                <th scope="col">Descripcion</th>
                                <th scope="col">Tipo</th>
                                <th scope="col">Fecha</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(var mov in @ViewData["movimientos"] as IEnumerable<Billetera2.Models.Movimiento>)
                            {
                            <tr>
                                <td>
                                    $@mov.Monto
                                </td>
                                <td>
                                    @mov.Descripcion
                                </td>
                                <td>
                                    @mov.TipoMovimiento
                                </td>
                                <td>
                                    @mov.Fecha
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>



<!--<div>
    <a class="btn btn-primary" asp-controller="Movimiento" asp-action="Index">Ver Movimientos</a> 
    <a class="btn btn-primary" asp-action="Edit">Editar credenciales</a>--> 

    <!--<a asp-action="Index">Back to List</a>-->
<!--</div>-->

Billetera2/Views/Usuario/Edit.cshtml
@model Billetera2.Models.Usuario

@{ ViewData["Title"] = "Edit"; }

<h1>Editar usuario</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" required/>
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contrasenia" class="control-label">Contraseña</label>
                <input asp-for="Contrasenia" class="form-control" required type="password"/>
                <span asp-validation-for="Contrasenia" class="text-danger" ></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Billetera2/Views/Usuario/Index.cshtml
@model IEnumerable<Billetera2.Models.Usuario>

@{ ViewData["Title"] = "Index"; }

<h1>Index</h1>

<p>
    <a asp-action="Create">Create Nuevo Usuario</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contrasenia)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Nombre)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Contrasenia)
    </td>
    <td>
        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
        <a asp-controller="Movimiento" asp-action="Index" asp-route-id="@item.Id">Movimientos</a> |
        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
    </td>
</tr>
        }
    </tbody>
</table>

Billetera2/Views/Usuario/Index1.cshtml
@model Billetera2.Models.Usuario
@*

    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Index1">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contrasenia" class="control-label"></label>
                <input asp-for="Contrasenia" type="password" class="form-control" />
                <span asp-validation-for="Contrasenia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Sign in" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Billetera2/Views/Usuario/Login.cshtml
@model Billetera2.Models.Usuario
@*

    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h4 class="text-center">Billetera</h4>

<div class="row justify-content-center">
    <div class="col-md-4 flex-column">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control"  required/>
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contrasenia" class="control-label">Contraseña</label>
                <input asp-for="Contrasenia" type="password" class="form-control" required />
                <span asp-validation-for="Contrasenia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Acceder" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Billetera2/Views/Usuario/Movimientos.cshtml
@model Billetera2.Models.Movimiento;


@{ ViewData["Title"] = "Crear Movimiento"; }

<h1>Añadir nuevo movimientos</h1>


<div class="row">
    <div class="col-md-4">
        <form asp-action="AddMovimiento">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Monto" class="control-label"></label>
                <input asp-for="Monto" class="form-control" />
                <span asp-validation-for="Monto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoMovimiento" class="control-label"></label>
                <input asp-for="TipoMovimiento" class="form-control" />
                <span asp-validation-for="TipoMovimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Añadir" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Movimientos">Volver a mis movimientos</a>
</div>